### ISSUE TITLE
在第五章的例子中

### ISSUE THREAD

**Issue by luckilyj** [FederatedAI/Practicing-Federated-Learning#5]
Traceback (most recent call last):
25
  File "./fate/python/fate_flow/operation/task_executor.py", line 168, in run_task
26
    run_object.run(component_parameters_on_party, task_run_args)
27
  File "./fate/python/federatedml/model_base.py", line 98, in run
28
    this_data_output = func(*real_param)
29
  File "./fate/python/federatedml/util/data_io.py", line 886, in fit
30
    data_inst = self.reader.read_data(data_inst, "fit")
31
  File "./fate/python/federatedml/util/data_io.py", line 139, in read_data
32
    input_data_labels = input_data.mapValues(lambda value: value.split(self.delimitor, -1)[self.label_idx])
33
  File "./fate/python/fate_arch/common/profile.py", line 282, in _fn
34
    rtn = func(*args, **kwargs)
35
  File "./fate/python/fate_arch/computing/standalone/_table.py", line 93, in mapValues
36
    return Table(self._table.mapValues(func))
37
  File "./fate/python/fate_arch/_standalone.py", line 141, in mapValues
38
    return self._unary(func, _do_map_values)
39
  File "./fate/python/fate_arch/_standalone.py", line 233, in _unary
40
    func, do_func, self._partitions, self._name, self._namespace
41
  File "./fate/python/fate_arch/_standalone.py", line 407, in _submit_unary
42
    results = [r.result() for r in futures]
43
  File "./fate/python/fate_arch/_standalone.py", line 407, in <listcomp>
44
    results = [r.result() for r in futures]
45
  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 425, in result
46
    return self.__get_result()
47
  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
48
    raise self._exception
49
IndexError: list index out of range

**Comment by innovation-cat** [comment]
FATE相关的问题，请按照页面的提示，添加页面中的FATE助手咨询（https://github.com/FederatedAI/Practicing-Federated-Learning/tree/main/chapter05_FATE_HFL）。另外，本书不是专门介绍FATE的书籍，如果想学习FATE，建议按照最新的官方文档来学习，因为版本不同可能配置也会有不一样的地方：

https://github.com/FederatedAI/FATE/blob/master/README_zh.md

**Comment by innovation-cat** [comment]
FATE相关的问题，请按照页面的提示，添加页面中的FATE助手咨询（ https://github.com/FederatedAI/Practicing-Federated-Learning/tree/main/chapter05_FATE_HFL ）。另外，本书不是专门介绍FATE的书籍，如果想学习FATE，建议按照最新的官方文档来学习，因为版本不同可能配置也会有不一样的地方：

https://github.com/FederatedAI/FATE/blob/master/README_zh.md

**Comment by gaolje** [comment]
> Traceback (most recent call last): 25 File "./fate/python/fate_flow/operation/task_executor.py", line 168, in run_task 26 run_object.run(component_parameters_on_party, task_run_args) 27 File "./fate/python/federatedml/model_base.py", line 98, in run 28 this_data_output = func(*real_param) 29 File "./fate/python/federatedml/util/data_io.py", line 886, in fit 30 data_inst = self.reader.read_data(data_inst, "fit") 31 File "./fate/python/federatedml/util/data_io.py", line 139, in read_data 32 input_data_labels = input_data.mapValues(lambda value: value.split(self.delimitor, -1)[self.label_idx]) 33 File "./fate/python/fate_arch/common/profile.py", line 282, in _fn 34 rtn = func(*args, **kwargs) 35 File "./fate/python/fate_arch/computing/standalone/_table.py", line 93, in mapValues 36 return Table(self._table.mapValues(func)) 37 File "./fate/python/fate_arch/_standalone.py", line 141, in mapValues 38 return self._unary(func, _do_map_values) 39 File "./fate/python/fate_arch/_standalone.py", line 233, in _unary 40 func, do_func, self._partitions, self._name, self._namespace 41 File "./fate/python/fate_arch/_standalone.py", line 407, in _submit_unary 42 results = [r.result() for r in futures] 43 File "./fate/python/fate_arch/_standalone.py", line 407, in 44 results = [r.result() for r in futures] 45 File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 425, in result 46 return self.__get_result() 47 File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result 48 raise self._exception 49 IndexError: list index out of range
请问现在解决这个问题了么，我也遇到了

**Comment by luckilyj** [comment]
还没解决，好久都不看联邦学习了
















At 2022-05-19 15:03:57, "gaolje" ***@***.***> wrote:

Traceback (most recent call last): 25 File "./fate/python/fate_flow/operation/task_executor.py", line 168, in run_task 26 run_object.run(component_parameters_on_party, task_run_args) 27 File "./fate/python/federatedml/model_base.py", line 98, in run 28 this_data_output = func(*real_param) 29 File "./fate/python/federatedml/util/data_io.py", line 886, in fit 30 data_inst = self.reader.read_data(data_inst, "fit") 31 File "./fate/python/federatedml/util/data_io.py", line 139, in read_data 32 input_data_labels = input_data.mapValues(lambda value: value.split(self.delimitor, -1)[self.label_idx]) 33 File "./fate/python/fate_arch/common/profile.py", line 282, in _fn 34 rtn = func(*args, **kwargs) 35 File "./fate/python/fate_arch/computing/standalone/_table.py", line 93, in mapValues 36 return Table(self._table.mapValues(func)) 37 File "./fate/python/fate_arch/_standalone.py", line 141, in mapValues 38 return self._unary(func, _do_map_values) 39 File "./fate/python/fate_arch/_standalone.py", line 233, in _unary 40 func, do_func, self._partitions, self._name, self._namespace 41 File "./fate/python/fate_arch/_standalone.py", line 407, in _submit_unary 42 results = [r.result() for r in futures] 43 File "./fate/python/fate_arch/_standalone.py", line 407, in 44 results = [r.result() for r in futures] 45 File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 425, in result 46 return self.__get_result() 47 File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result 48 raise self._exception 49 IndexError: list index out of range
请问现在解决这个问题了么，我也遇到了

**Comment by gaolje** [comment]
好的，感谢回复



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月19日(周四) 下午4:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [FederatedAI/Practicing-Federated-Learning] 在第五章的例子中 (Issue #5)




 还没解决，好久都不看联邦学习了
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 At 2022-05-19 15:03:57, "gaolje" ***@***.***&gt; wrote:
 
 Traceback (most recent call last): 25 File "./fate/python/fate_flow/operation/task_executor.py", line 168, in run_task 26 run_object.run(component_parameters_on_party, task_run_args) 27 File "./fate/python/federatedml/model_base.py", line 98, in run 28 this_data_output = func(*real_param) 29 File "./fate/python/federatedml/util/data_io.py", line 886, in fit 30 data_inst = self.reader.read_data(data_inst, "fit") 31 File "./fate/python/federatedml/util/data_io.py", line 139, in read_data 32 input_data_labels = input_data.mapValues(lambda value: value.split(self.delimitor, -1)[self.label_idx]) 33 File "./fate/python/fate_arch/common/profile.py", line 282, in _fn 34 rtn = func(*args, **kwargs) 35 File "./fate/python/fate_arch/computing/standalone/_table.py", line 93, in mapValues 36 return Table(self._table.mapValues(func)) 37 File "./fate/python/fate_arch/_standalone.py", line 141, in mapValues 38 return self._unary(func, _do_map_values) 39 File "./fate/python/fate_arch/_standalone.py", line 233, in _unary 40 func, do_func, self._partitions, self._name, self._namespace 41 File "./fate/python/fate_arch/_standalone.py", line 407, in _submit_unary 42 results = [r.result() for r in futures] 43 File "./fate/python/fate_arch/_standalone.py", line 407, in 44 results = [r.result() for r in futures] 45 File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 425, in result 46 return self.__get_result() 47 File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result 48 raise self._exception 49 IndexError: list index out of range
 请问现在解决这个问题了么，我也遇到了

**Comment by gaolje** [comment]
重新上传数据集，配置数据上传文件时，重新命名table_name，namespace（注意不能与之前名字重复）。再次提交任务就🆗了，我之前多次对同一个table_name，namespace上传数据，可能是这个原因导致这个错误。

**Comment by luckilyj** [comment]
好滴，多谢，多谢。
















在 2022-05-20 16:06:12，"gaolje" ***@***.***> 写道：

重新上传数据集，配置数据上传文件时，重新命名table_name，namespace（注意不能与之前名字重复）。再次提交任务就了，我之前多次对同一个table_name，namespace上传数据，可能是这个原因导致这个错误。
